name: Manifest Build

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test & Build
        run: |
          pnpm build
          pnpm test
        shell: bash
        env:
          CI: true
